pjt0908/accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),


]

pjt0908/cong/urls.py
from django.urls import path
from . import views

app_name='cong'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),

]

pjt0908/joy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cong/', include('cong.urls')),
    path('accounts/', include('accounts.urls')),
]

pjt0908/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

pjt0908/cong/models.py
from django.db import models

# Create your models here.
class Maru(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

pjt0908/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

#USER 재정의 후 장고의 기존 Form 사용시 default로 사용하던 'auth.Form'이 아니므로 에러가 발생
#새로 정의한 'accounts.User'를 생성할 수 있도록 Form 재정의
#아래 코드 : 기존 'auth.forms'에서 사용하는 UserCreationForm의 기능을 모두 가져온 뒤 model만 우리가 정의한 모델로 바꿈.
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ['email', 'first_name']

pjt0908/cong/forms.py
from django import forms
from .models import Maru

#form class
# - 모델에 없는 값을 입력받고 싶을 때 

#modelform class
# - 모델이 있는 값만 입력받고 싶을 때 
class MaruForm(forms.ModelForm):
    #이 클래스를 설명하는 클래스 - Meta
    class Meta:
        model = Maru
        #사용자의 입력을 원하는 필드종류
        fields = '__all__'
        #exclude

pjt0908/accounts/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request,user)
            return redirect('cong:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form':form,
    }
    return render(request, 'accounts/signup.html', context)


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('cong:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('cong:index')

def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('cong:index')

def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('cong:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form':form,
    }
    return render(request, 'accounts/update.html', context)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            #비밀번호 변경 후 로그아웃 되지 않도록 session 정보 업데이트 후 정보를 
            update_session_auth_hash(request, form.user)
            return redirect('cong:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form':form,
    }
    return render(request,'accounts/change_password.html', context)

pjt0908/cong/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Maru
from django.views.decorators.http import require_http_methods,require_POST
from .forms import MaruForm

# Create your views here.
def index(request):
    maru = Maru.objects.all()
    context = {
        'maru' : maru,
    }
    return render(request, 'cong/index.html', context)

#GET, POST 2가지 http method 요청이 들어오므로, 데코레이터 사용
@require_http_methods(['GET','POST'])
def create(request):
    #사용자의 입력 후 요청이 왔을 때
    if request.method =='POST':
        form = MaruForm(request.POST)
        #유효성검사
        if form.is_valid():
            #form.save()는 객체를 반환한다
            maru = form.save()
            return redirect('cong:index')
    #사용자가 처음으로 생성 페이지에 접근했을 때
    else:
        #form을 만들고
        form = MaruForm()
    context={
        'form':form,
    }
    return render(request, 'cong/create.html', context)

def detail(request, pk):
    # maru = Maru.objects.get(pk=pk)
    # get_object_or_404 = 데이터를 조회하지 못하면 404에러를 띄워라
    # 일반적으로 웹에서 없는 데이터 조회시 404 에러를 띄움
    # 웹 서버랑 연동하게 되면 더 자세히 이해할 수 있음
    maru = get_object_or_404(Maru, pk=pk)
    context = {
        'maru':maru,
    }

    return render(request, 'cong/detail.html', context)


@require_http_methods(['GET','POST'])
def update(request,pk):
    maru=get_object_or_404(Maru,pk=pk)
    if request.method == 'POST':
        form = MaruForm(request.POST, instance=maru)
        if form.is_valid():
            form.save()
            return redirect('cong:detail', maru.pk)
    else:
        form = MaruForm(instance=maru)
    context = {
        'maru':maru,
        'form':form,
    }
    return render(request, 'cong/update.html', context)

@require_POST
def delete(request,pk):
    maru=get_object_or_404(Maru,pk=pk)
    maru.delete()
    return redirect('cong:index')

pjt0908/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
    <h1>CHANGE_PWD</h1>
    <hr>

    <form action="{% url 'accounts:change_password' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value='작성하기'>
    </form>

{% endblock content %}

pjt0908/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>LOGIN</h1>
    <hr>

    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value='로그인'>
    </form>

    <a href="{%url 'cong:index' %}">BACK</a>
{% endblock content %}

pjt0908/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
    <h1>SIGN UP</h1>
    <hr>

    <form action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value='작성하기'>
    </form>

{% endblock content %}

pjt0908/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
    <h1>UPDATE</h1>
    <hr>

    <form action="{% url 'accounts:update' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value='업데이트'>
    </form>

{% endblock content %}

pjt0908/cong/templates/cong/create.html
{% extends 'base.html' %}

{% block content %}
    <h1>Create Page</h1>
    <hr>

    <form action="{% url 'cong:create' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value='작성하기'>
    </form>

{% endblock content %}

pjt0908/cong/templates/cong/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>DETAIL</h1>
    <hr>
    <p> PK : {{maru.pk}} </p>
    <p> TITLE : {{maru.title}} </p>
    <p> CONTENT : {{maru.content}} </p>
    <p> CREATED_at : {{maru.created_at}} </p>
    <p> UPDATED_at : {{maru.updated_at}} </p>
    <hr>
    <a href="{% url 'cong:update' maru.pk %}">UPDATE</a>
    <a href="{% url 'cong:index' %}">BACK</a>

    <form action="{% url 'cong:delete' maru.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="DELETE">
    </form>
{% endblock content %}

pjt0908/cong/templates/cong/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>INDEX</h1>
    <a href="{% url 'cong:create' %}">글 작성하기</a>
    <hr>
    {% for mm in maru %}
        
        <a href="{% url 'cong:detail' mm.pk %}"><p> PK : {{mm.pk}} </p></a>
        <p> TITLE : {{mm.title}} </p>
        <p> CONTENT : {{mm.content}} </p>
        <hr>
        
    {% endfor %}

{% endblock content %}

pjt0908/cong/templates/cong/update.html
{% extends 'base.html' %}

{% block content %}
    <h1>UPDATE</h1>
    <hr>
    <form action="{% url 'cong:update' maru.pk %}" method="POST">
        {% csrf_token %}
        <label for="title">Title : </label>
        <input type="text" name="title" value={{ maru.title }}> <br>
        <label for="content" name="content" >CONTENT : </label>
        <textarea name="content" id="content" cols="30" rows="10">{{maru.content}}</textarea>
        <input type="submit">
    </form>

    <a href="{% url 'cong:index' %}">BACK</a>
{% endblock content %}

pjt0908/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <h2>Hello, {{user}}</h2>
    <hr>
    <a href="{% url 'accounts:signup' %}">회원가입</a>
    <a href="{% url 'accounts:delete' %}">회원삭제</a>
    <a href="{% url 'accounts:update' %}">회원수정</a>
    <a href="{% url 'accounts:login' %}">로그인</a>
    <a href="{%url 'accounts:logout' %}">로그아웃</a>
    {% block content %}
    {% endblock content %}

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>